version: "3.8"

x-api: &payment-api-template
  build: ./payment-api # TODO: change build files to published images on docker hub
  depends_on:
    redis:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: "0.2"
        memory: "40MB"
  environment:
    - PAYMENTS_QUEUE=payments
    - REDIS_URL=redis://redis:6379
    - PROCESS_PAYMENT_JOB_NAME=process-payment
  networks:
    - rinha-backend
    # TODO: uncomment payment-processor
    # - payment-processor

x-worker: &payment-worker-template
  build: ./payment-worker
  deploy:
    resources:
      limits:
        cpus: "0.25"
        memory: "70MB"
  depends_on:
    redis:
      condition: service_healthy
  networks:
    - rinha-backend
    # - payment-processor

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-api-01
      - payment-api-02
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
      # - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  payment-api-01:
    <<: *payment-api-template
    hostname: payment-api-01
    container_name: payment-api-01

  payment-api-02:
    <<: *payment-api-template
    hostname: payment-api-02
    container_name: payment-api-02

  payment-worker-01:
    <<: *payment-worker-template
    hostname: payment-worker-01
    container_name: payment-worker-01

  payment-worker-02:
    <<: *payment-worker-template
    hostname: payment-worker-02
    container_name: payment-worker-02

  healthcheck-worker:
    build: ./healthcheck-worker
    hostname: healthcheck-worker
    container_name: healthcheck-worker
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - rinha-backend
      # - payment-processor

  dlq-worker:
    build: ./dlq-worker
    hostname: dlq-worker
    container_name: dlq-worker
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"
    networks:
      - rinha-backend
      # - payment-processor

  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"
    networks:
      - rinha-backend

networks:
  rinha-backend:
    driver: bridge
  # payment-processor:
  #   external: true
